jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '65cd84b588'
          channel: 'master'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          sudo apt update
          sudo apt install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt install -y clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
          flutter build linux --release
  relase:
    needs: build_linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: app-release
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            app-release/build/linux/release/bundle/*
on: push
