on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '65cd84b588'
          channel: 'master'
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: |
          sudo apt update
          sudo apt install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt install -y clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
          flutter build linux --release
          zip -r build/linux/linux.zip build/linux/x64/release/bundle/
      - uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/linux/linux.zip
  release:
    needs: [build_linux, build_windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: app-release
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            linux.zip
            windows.zip
            

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '65cd84b588'
          channel: 'master'
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: |
          flutter build windows --release
          Compress-Archive -Path build\windows\runner\Release -DestinationPath build\windows\windows.zip
      - uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: app-release
          path: build/windows/windows.zip